### ISSUE TITLE
Unable to run from outside particleviz directory

### ISSUE THREAD

**Issue by erikvansebille** [olmozavala/particleviz#8]
I don't seem to be able to run particleviz from outside the `particleviz` directory. 

For example, if I run `python ~/Codes/particleviz/ParticleViz.py --input_file argo_float.nc`, I get 
```
Initializing webapp...
Traceback (most recent call last):
  File "/Users/erik/Codes/particleviz/ParticleViz.py", line 64, in <module>
    shutil.copyfile("Current_Config.json", join("ParticleViz_WebApp","src","Config.json"))
  File "/opt/anaconda3/envs/particleviz/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'ParticleViz_WebApp/src/Config.json'
```

**Comment by olmozavala** [comment]
It seems to be working correctly now.
